services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6969:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      custom:
        ipv4_address: 10.5.0.5
networks:
  custom:
    driver: bridge
    name: custom
    external: true
    ipam:
      config: 
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1