version: '16.2'

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6969:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  #pgadmin:
  #  image: dpage/pgadmin4
    #restart: always
    #environment:
      #PGADMIN_DEFAULT_EMAIL: postgres@email.com
      #PGADMIN_DEFAULT_PASSWORD: postgres
    #ports:
      #- "5050:80"